package com.ciphertechsolutions.io.logging;

/**
 * An enum for the types of messages in the application.
 */
public enum LogMessageType {
    /**
     * An error message.
     */
    ERROR,
    /**
     * A warning message.
     */
    WARNING,
    /**
     * An info message.
     */
    INFO,
    /**
     * A message for the user.
     */
    USER,
    /**
     * A message to help with debugging.
     */
    DEBUG,
    /**
     * A message to show in the report generated by ION during drive imaging.
     */
    REPORT,   
    /**
     * A GPS message to write out to CSV
     */
    GPS;

}
